# Site settings
title: TIMBABWE
email: allegro@conmolto.org
description: "the life and work of tim krajcar: technologist, husband, father, and musician in portland, oregon"
baseurl: ""
url: "http://www.timbabwe.com"
twitter_username: TimKrajcar
github_username:  tkrajcar

# Build settings
markdown: kramdown
permalink: "/:year/:month/:title/"
highlighter: pygments

gems:
  - jekyll-sitemap
